### ISSUE TITLE
My country, Mauritius, is missing and I would like to help

### ISSUE THREAD

**Issue by avinash** [dylantelson/amusicalplanet#1]
Hi Dylan,

I've noticed that my country, Mauritius, is missing and I would like to help. [Séga](https://en.wikipedia.org/wiki/Sega_(genre)) is the typical music genre of Mauritius but [Seggae](https://en.wikipedia.org/wiki/Seggae) is also popular.

I can help by identifying, say, 5 good séga songs and 5 good seggae songs on Spotify.

Would you be interested?

Avinash

**Comment by dylantelson** [comment]
Hey Avinash, that would be great :) If you want to create a Spotify playlist and send it to me, I could add any songs from there to the website.
